### ISSUE TITLE
Snapshot controller and Volsync should be addons

### ISSUE THREAD

**Issue by alex-matthews** [onedr0p/flux-cluster-template#1121]
Since VolSync now comes by default it would be nice to have some guidance around its use/implementation.

**Comment by onedr0p** [comment]
I was actually thinking of making this and the snapshot-controller a single addon as it's not required.

**Comment by alex-matthews** [comment]
Makes sense - not everyone needs it and placing too much emphasis on it runs into a concern you recently articulated in https://github.com/onedr0p/flux-cluster-template/discussions/838#discussioncomment-8007868

> Unfortunately that would require Minio or R2 to be set up and rook or longhorn to be mandatory to set up and I like to leave storage options open for the user to implement themselves.

**Comment by onedr0p** [comment]
done in https://github.com/onedr0p/flux-cluster-template/commit/8e7d36c0c587ac424d6568b55b1c284dea7a4e54
