### ISSUE TITLE
Add Gatus as a addon or core component

### ISSUE THREAD

**Issue by alex-matthews** [onedr0p/flux-cluster-template#1122]
Not sure how feasible this is, but both Gatus and Authelia would make great add-ons imo.

**Comment by onedr0p** [comment]
Gatus seems like a good idea, however I am not sure about Authelia. I would like people to add support for OIDC themselves since there are other tools out there.

**Comment by alex-matthews** [comment]
To me Gatus is a ripe candidate in that it (a) involves much templating (b) needn't store state (c) provides really useful observability and (d) complements other tools.

Regarding Authelia, there has been recent discussion in the Discord server about lightweight/basic deployments of it. One community member reports:

> I just run Authelia "stateless" with configmap containing the user hashes, no DB.
Single replica but with rolling restarts there is no downtime.

Could such a deployment form an optional addon for those who want a simple auth solution, or are there still too many knobs and dials?

I struggle with all the overlapping definitions/concepts/acronyms that dominate this space. Is OIDC the de facto standard? Does it require IdP integration? Does all this mean there can be no "one size fits all" opinionated approach?

Also, any thoughts about Cloudflare Zero Trust? Given the template already leverages Cloudflare Tunnels it seems logical... I'm not at all familiar with it though.

**Comment by onedr0p** [comment]
> To me Gatus is a ripe candidate in that it (a) involves much templating (b) needn't store state (c) provides really useful observability and (d) complements other tools.

Agreed!

> Could such a deployment form an optional addon for those who want a simple auth solution, or are there still too many knobs and dials?

Pretty much that, there's a lot of configuration to template out however I am not completely dismissing the idea. Like storage OIDC is opinionated between Authentik, Zitadel, Keycloak and others.

> I struggle with all the overlapping definitions/concepts/acronyms that dominate this space. Is OIDC the de facto standard? Does it require IdP integration? Does all this mean there can be no "one size fits all" opinionated approach?

If the application supports OIDC there's a pretty good chance those apps I named above could support it but not 100%.

> Also, any thoughts about Cloudflare Zero Trust? Given the template already leverages Cloudflare Tunnels it seems logical... I'm not at all familiar with it though.

I am not not familiar with it or have thought about using it tbh.

**Comment by onedr0p** [comment]
I am not sure how much I want to go down the path of adding a ton of addons. I am going to close this issue for now but maybe in the future there could be a community supported repo just for addons to this template.
