### ISSUE TITLE
Validating kustomizations yields "found character that cannot start any token"

### ISSUE THREAD

**Issue by giannoug** [onedr0p/flux-cluster-template#1211]
Fetching latest changes to my repo (and nuking / rebuilding the cluster) introduced a couple of errors. This is an example of these, I've fixed a couple of them.
```
=== Validating kustomizations in /workspaces/azazel/kubernetes/apps/networking/nginx/certificates/ ===
Error: invalid Kustomization: yaml: line 7: found character that cannot start any token
task: Failed to run task "configure": exit status 1
```
Here's what `kustomization.yaml` looks like:
```
#jinja2: trim_blocks: True, lstrip_blocks: True
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./staging.yaml
  {% if bootstrap_acme_production_enabled | default(false) %}
  - ./production.yaml
  {% endif %}
```

It has something to do with Jinja(?) and `#%` versus `{%` in `kustomization.yaml.j2`. I've been fixing files as I go and I can open a PR when done, but it that really an issue on the latest changes or in my local env?

**Comment by giannoug** [comment]
Not an issue with the repo, it seems that [my way of staying up with the template](https://github.com/onedr0p/flux-cluster-template/discussions/838#discussioncomment-8007492) doesn't delete files. Files that have issues in my repo don't exists in the template (anymore)

**Comment by onedr0p** [comment]
Yeah sorry for the major changes lately it's in the middle of being refactored with makejinja fur templating and validation
