### ISSUE TITLE
Cluster user secrets not removed from template

### ISSUE THREAD

**Issue by xoredg** [onedr0p/flux-cluster-template#1250]
Picked a bad time to try this project, but here I am trying to do as little as I can to make it better ;)

Apparently there was a change on #1245 that removed a couple of user-specific files from the template, but they're still being reference in the tasks, so as a result the flux cluster can't get bootstrapped. 

I'm not sure how to refresh the template if there's ever a fix (noob moment), but for now I'm commenting these lines on the Taskfile and praying. :joy:

**Comment by onedr0p** [comment]
Fixed in https://github.com/onedr0p/flux-cluster-template/commit/98583949f8852af6ae1a59b5d10a4549e378f195

Thanks for reporting!
