### ISSUE TITLE
What is the intended workflow for adding new charts?

### ISSUE THREAD

**Issue by AskAlice** [onedr0p/flux-cluster-template#436]
# Details

**Ask your question:**
I was reading the flux docs and I read that certain kustomizations can get overwritten by flux, which kind of implies that flux keeps track of where its yamls are
at the moment I've just been copying the output of these into new files.
```
flux create source git flux-monitoring \
  --interval=30m \
  --url=https://github.com/fluxcd/flux2 \
  --branch=main --export

# some yaml here

flux create kustomization kube-prometheus-stack \
  --interval=1h \ 
  --prune \                              
  --source=flux-monitoring \
  --path="./manifests/monitoring/kube-prometheus-stack" \
  --health-check-timeout=5m \ 
  --export

# some yaml here
  ````
  
But is there a different/more robust way? I noticed that the `apiVersion` of your yamls doesn't really show `kustomize.toolkit.fluxcd.io/v1beta2`

Also, at the moment I think when I run those commands it actually creates the resource in my cluster, which is probably not intended.

**Comment by onedr0p** [comment]
Hi @AskAlice 

This repo doesn't really use the flux commands to create resources and instead I create the resources from scratch or by copy/pasting & updating chart values from ideas taken from https://whazor.github.io/k8s-at-home-search/

> But is there a different/more robust way? I noticed that the apiVersion of your yamls doesn't really show kustomize.toolkit.fluxcd.io/v1beta2

Not every application needs to have a fluxtomization, for example [this](https://github.com/k8s-at-home/flux-cluster-template/blob/main/cluster/flux/apps.yaml) fluxtomize applies everything under the [./cluster/apps](https://github.com/k8s-at-home/flux-cluster-template/tree/main/cluster/apps) folder
