### ISSUE TITLE
when kube-vip is false in .config.env use node ip address.

### ISSUE THREAD

**Issue by Haasie** [onedr0p/flux-cluster-template#478]
# Details
OS: Fedora 36
Install single node k3s 

Following the steps from the README.md provided by the template, i run into an issue when try to connect to my node. 

It appears that when u set ```BOOTSTRAP_KUBE_VIP_ENABLED='false'``` you should replace the ip address in ./provision/kubeconfig to your node ip address (The address you filled in at ```BOOTSTRAP_ANSIBLE_HOST_ADDR_0=```)

**Comment by onedr0p** [comment]
Closing due to https://github.com/onedr0p/flux-cluster-template/issues/555
