### ISSUE TITLE
kustomize build failed for system upgrade controller

### ISSUE THREAD

**Issue by osnabrugge** [onedr0p/flux-cluster-template#491]
I have performed a fresh install following your guide (nuked and redeployed several times to reproduce) and it appears that bootstrapping the cluster fails with kustomize giving an error on system upgrade controller being unable to retrieve a file or directory via git cmd.  Any ideas how to resolve this?

Thank you in advance & appreciate your hard work as this is one of the few well documented home labs.

![Screenshot 2022-10-11 074217](https://user-images.githubusercontent.com/18647660/195080816-f80ffa45-cf9e-462b-8906-0fe1ef039c49.png)

**Comment by onedr0p** [comment]
From my investigation it seems like those errors are intermittent and it appears to be an issue with flux trying to use kustomize to git clone the CRDs. I haven't discovered a fix outside doing that a completely other way.

**Comment by osnabrugge** [comment]
Thank you for the quick response.  It appears that you have github,com/rancher/system-upgrade-controller?ref=v0.9.1 defined as a resource.  How do you suggest I modify the install?  Anything besides commenting it out or removing it?
![Screenshot 2022-10-11 075930](https://user-images.githubusercontent.com/18647660/195083886-8dbfbd5e-08d1-478d-a1c8-accce8af6bb9.png)

**Comment by onedr0p** [comment]
That line brings in the CRDs and deployment, so removing it would delete those resources. I'm my personal repo I'm doing the same thing but I mitigated it a bit by changing the flux reconciling on the apps kustomization.

https://github.com/onedr0p/home-ops/commit/ec2de00321299342c5c7996487485628c32523c8

**Comment by osnabrugge** [comment]
Still at a complete loss.   I have no idea how to resolve this issue to get system-upgrade-controller or any of the other applications working.  I've tried manually deploying by kubectl apply --kustomize directly on basically each folder without any success beyond metallb and k8s-gateway.  Even sops appears funky and doesn't function for cloudflareddns (external-dns deploys, but doesn't retrieve it's secret credentials).  I might just clone your personal repo or one of the others and go from there now that I understand a bit more how the whole GitOps processes work (still a lot to learn, but I think I grasp the high-level).

**Comment by onedr0p** [comment]
If you want to continue without running the system-upgrade-controller, comment it out here.

https://github.com/onedr0p/flux-cluster-template/blob/320f34fc2b1d3edcd660dda1313c8c6e22567eda/cluster/apps/kustomization.yaml#L9

That should get you further into the rollout of the deployments without it holding you up.

**Comment by osnabrugge** [comment]
Thank you!  That solved the issue and I'll close this out.
