### ISSUE TITLE
perl-bignum dependency missing

### ISSUE THREAD

**Issue by PrymalInstynct** [onedr0p/flux-cluster-template#498]
# Details

**OS:** Fedora 36 Server (Fresh Install)

Following the guide to a T I ran into an issue when executing `task verify` it produced the following error.

```
Can't locate bignum.pm in @INC (you may need to install the bignum module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/linuxbrew/.linuxbrew/bin/ipcalc line 23.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/bin/ipcalc line 23.
```

I had to install `perl-bignum` via DNF to get the dependency in place.

I am not sure if this is a result of the way homebrew packages `ipcalc` or is something that needs to be included in the Template README to ensure is installed.

**Comment by onedr0p** [comment]
Workstation CLI dependencies are hard to automate the installation of, homebrew comes close as a AIO solution but as you found out you needed a package on a specific OS. I am glad you have found the solution. Distributing CLI apps on Linux using a certain package manager is a huge PITA, every distro has their opinions.

I am sure it will help out other folks using Fedora Workstation and Homebrew.
