### ISSUE TITLE
Character '!' not allowed in .config.env

### ISSUE THREAD

**Issue by Venoox** [onedr0p/flux-cluster-template#556]
# Details

I was debugging this for hours and couldn't understand why `ansible:ping` is saying `missing sudo password` and it turns out it was because my node password contained character '!'. Not sure why that happens, but just wanted to report this "bug" so other people don't waste their time.

**Comment by onedr0p** [comment]
Thanks for mentioning this, a good takeaway is it's always good to only use alphanumerics in passwords.
