### ISSUE TITLE
External-DNS assigns local ip

### ISSUE THREAD

**Issue by mdegouw** [onedr0p/flux-cluster-template#566]
I just created an test with this template and its working great, however i'm running against an issue with external-dns.

External-dns is setting my internal ip on cloudflare. I understand this is because it sets the loadbalancer IP assigned to nginx service.
I have been unable to find any information regarding a fix, so i was wondering how you did this @onedr0p 
![image](https://user-images.githubusercontent.com/3748069/209451700-bc441bde-b239-47bb-8e88-ffc4f86fb532.png)

**Comment by onedr0p** [comment]
Looks like I had a bad copy paste from my repo 😅

Try making the changing I just committed

https://github.com/onedr0p/flux-cluster-template/commit/08040e3e491fb7bad7bf31c79723b81c605598b4

https://github.com/onedr0p/flux-cluster-template/commit/0a5dfb361e8417aa08aa92aae315b9e9e3b47aba

**Comment by mdegouw** [comment]
Tnx `external-dns.alpha.kubernetes.io/target` did the trick ;)

It does however look like i need to use the annotation `external-dns.home.arpa/enabled: "true"` instead of `external-dns/is-public: "true"`.

Cuz i had to change it at the webhook flux addon before external-dns picked it up.
And i just tested it with all your changes and it does indeed delete all records.
![image](https://user-images.githubusercontent.com/3748069/209452340-3035c061-1ea0-4274-96bc-e5bf5f91b86f.png)

**Comment by onedr0p** [comment]
Right that was the old annotation I used for that. I made another commit for fixing up a few more nits
https://github.com/onedr0p/flux-cluster-template/commit/73237942a0f7f27fe19a70611421e24bc03d5a51

**Comment by mdegouw** [comment]
Great, keep up the amazing work 😁
