### ISSUE TITLE
Use ansible to manage cloudflare dns

### ISSUE THREAD

**Issue by mrueg** [onedr0p/flux-cluster-template#567]
Using https://docs.ansible.com/ansible/latest/collections/community/general/cloudflare_dns_module.html  would simplify the project by removing the terraform dependency.

**Comment by onedr0p** [comment]
I thought about this awhile ago but I want to stick with Terraform.

- The terraform module is officially created and maintained by cloudflare.
- After the initial `terraform apply` there's not much else to do;
- However Terraform opens the door to better automation with tools like the Flux tf-controller which I've been thinking of including here by default.
- My love of Ansible is dwindling, I only find it useful for modifying the OS layer and if no other option exists some other things too.
- I'm not planning on this yet but if this project ever pivoted to Talos Linux, Ansible could be completely dropped.
