### ISSUE TITLE
kubectl direnv setup issues and solution

### ISSUE THREAD

**Issue by benwalio** [onedr0p/flux-cluster-template#573]
I'm new to k8s, so this is prob the dumbest issue in here, but still figured i'd share what i found in case any other dummies like me are coming across a similar issue!

Issue: 
- After going through the setup, trying to use `kubectl` kept resulting in:
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`

Notes:

After doing a little research, the k8s docs said to install minikube to get it to work, but this didn't seem right. Further reading on the linked reading materials led me to it being a config issue. When manually specifying the `--kubeconfig` var inside my `kubectl` calls, it was working fine. Read through the repo and found that `.envrc` file which _should_ have fixed everything for me. Going to `brew install direnv` resulted in a "It's already installed, idiot" message from homebrew. Finally, I figured out that I needed to hook the direnv call into my `~/.zshrc` file.

Process:

`kubectl cluster-info`

output: `The connection to the server localhost:8080 was refused - did you specify the right host or port?`

`brew install direnv`

output: `Warning: direnv 2.32.2 is already installed and up-to-date.`

```
echo 'eval "$(direnv hook zsh)"' >> ~/.zshrc
source ~/.zshrc
```

or

```
echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
source ~/.bashrc
```

output: `direnv: error [[redacted]]/.envrc is blocked. Run direnv allow to approve its content`

`direnv allow`

output:
```
direnv: loading [[redacted]]/.envrc                                                                                               
direnv: export +ANSIBLE_CONFIG +ANSIBLE_HOST_KEY_CHECKING +KUBECONFIG
```

`kubectl cluster-info`

output:
```
Kubernetes control plane is running at https://10.211.55.199:6443
CoreDNS is running at https://10.211.55.199:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

🎉

**Comment by onedr0p** [comment]
Thanks for the feedback, direnv isn't a requirement but maybe I should add the docs to make it so. The reason I didn't do this in the first place is not everyone uses the same shell.

FWIW there's a subtle hint already on the README under reading materials that links to how to set up the kubeconfig.

**Comment by benwalio** [comment]
All good! I just figured I'd share so hopefully some other person has an easier time of it. Honestly, direnv is a great tool - wish I had known about it sooner. And, I read through the hinted at documentation. The problem was - since I didn't initially know that the problem was a config issue, I didn't think to start messing with the config flags or reading up on the config. After some rooting around, it turns out that was it and the documentation helped me get it sorted.

But, maybe a line about "The kubectl configuration is in the `./kubeconfig` file, if you have issues with kubectl, double check that the config is being loaded" could be beneficial. 

overall though, was fun to set up the project! Really appreciate the steps. Now, I just gotta figure out what I'm going to do with it.

**Comment by onedr0p** [comment]
Thanks for the suggestion, done in https://github.com/onedr0p/flux-cluster-template/commit/8c9f8c0bd7f2ce5b8b819a8abde7cb40c6035449
