### ISSUE TITLE
intel-gpu-tools package absent in Fedora aarch

### ISSUE THREAD

**Issue by ChipWolf** [onedr0p/flux-cluster-template#574]
Ansible attempts to install the `intel-gpu-tools` package by default, this package appears to be absent in the aarch64 when testing on a Raspi

https://github.com/onedr0p/flux-cluster-template/blob/4e6edcc66a7cee52fb74d454bd36a55bfc600b85/ansible/inventory/group_vars/kubernetes/os.yml#L14

**Comment by onedr0p** [comment]
Fixed in https://github.com/onedr0p/flux-cluster-template/issues/574
