### ISSUE TITLE
nginx-ingress-controller, reloader, and cert-manager deploy multiple replicas by default with no spread constraints

### ISSUE THREAD

**Issue by ChipWolf** [onedr0p/flux-cluster-template#576]
If you run a single node, for whatever reason, these services will schedule multiple extraneous replicas to your node.

If you run a multi-node, there's a risk that all the replicas are deployed to a single node.

I propose setting topology spread constraints to remove multiple replicas being scheduled on one node. If that doesn't allow the deployment to reconcile correctly, additionally consider parameterization of the replica counts in some way or reference the caveat in the readme.

**Comment by onedr0p** [comment]
I might just scale these down to 1 and leave it up to people to scale if they want to in their clusters.

**Comment by onedr0p** [comment]
I choose to just keep everything at 1 replica.

https://github.com/onedr0p/flux-cluster-template/commit/ef4b12e66a46eb9c98622556003b689049e9979c
