### ISSUE TITLE
sops tasks broken

### ISSUE THREAD

**Issue by TheGor1lla** [onedr0p/flux-cluster-template#578]
The task docs state:  

```
* sops:d:                         Decrypt sops file 'to use must include -- before path to file.'  eg "task sops:d -- file.yaml"
* sops:e:                         Encrypt sops file 'to use must include -- before path to file.' eg "task sops:e -- file.yaml"
```
but using it returns an error:

```
gor1lla@rapture:~/git/private/homelab/terraform/cloudflare$ task sops:d -- secret.sops.yaml
task: [sops:d] sops --decrypt --in-place secret.sops.yaml
Error: cannot operate on non-existent file
task: Failed to run task "sops:d": exit status 100
```

**Comment by onedr0p** [comment]
Unless I'm missing something that error means your secret file is not found.

**Comment by TheGor1lla** [comment]
Does it work for you? The file is definitely there. Using `sops --decrypt --in-place secret.sops.yaml` itself works

**Comment by onedr0p** [comment]
Interesting, I honestly don't use it to be honest since the sops CLI is short enough to run without task.

**Comment by onedr0p** [comment]
I might end up removing the sops task as it's not really helpful. Feel free to use it in your own repo though if you can get it working.

**Comment by TheGor1lla** [comment]
I just stumbled over it. I use sops and kubectl commands directly.

Want me to open a PR?

**Comment by onedr0p** [comment]
Sure, if you don't mind.

**Comment by TheGor1lla** [comment]
That's the bare minimum I could do.  Love the template so far, already learned a lot

**Comment by onedr0p** [comment]
Awesome, and thanks!
