### ISSUE TITLE
Clarify Ansible part in README

### ISSUE THREAD

**Issue by starteleport** [onedr0p/flux-cluster-template#586]
Maybe I've misunderstood something, but I'm a bit confused with the header [Preparing Fedora Server with Ansible](https://github.com/onedr0p/flux-cluster-template#-preparing-fedora-server-with-ansible). Initially I thought that I could skip this section altogether and ran into problems that "K3S" Ansible role could not be found.

That's because the next section does not contain explicit step to run `task ansible:init`, however it's required in case these roles are missing.

Also, maybe there is something with my configuration, but I've had to run `sudo pip install --upgrade --user openshift` because I've had `error: No module named 'kubernetes'` during `ansible:install`

**Comment by onedr0p** [comment]
@starteleport I'm curious what was the reason you thought you could skip the `ansible:init` step?

Interesting on the pip thing, I'll have to verify. 

Thanks for the feedback!

**Comment by onedr0p** [comment]
> That's because the next section does not contain explicit step to run task ansible:init, however it's required in case these roles are missing.

I am not sure what you mean by that, the task is mentioned there...

<img width="857" alt="image" src="https://user-images.githubusercontent.com/213795/211206992-31cce915-9b64-40e5-8cb7-dd45a9b57d62.png">

**Comment by starteleport** [comment]
@onedr0p, thanks for the clarification! Regarding `kubernetes` module: I've had to install it on my workstation for the Ansible setup to work, not on the target node.

**Comment by onedr0p** [comment]
Cool, I updated the docs here

https://github.com/onedr0p/flux-cluster-template/commit/2ae3bc7cba88ffdf7e6b70e9535aea44fb3d90cd
