### ISSUE TITLE
Read write permissions GH actions 

### ISSUE THREAD

**Issue by Haasie** [onedr0p/flux-cluster-template#605]
After the first updates provided by renovate bot i was experiencing errors with the Meta labeler  action on GH.
The error said "Resource not accessible by integration". 

After some searched it seems that you need to provide read/write access for those actions in order to do there "job" 

Maybe worth mentioning in the Docs :smile:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/45860400/213405521-419fc7e1-95e0-4146-a193-29abcbf50993.png">

**Comment by onedr0p** [comment]
I believe this was done in https://github.com/onedr0p/flux-cluster-template/commit/8875a8b7069443b32c4d3a3eb121c1ea4c244916

**Comment by giannoug** [comment]
This doesn't automatically work, I cloned the repo yesterday and had to apply the permission fix myself to get the Action working 🤔 It failed until I gave it "Read and write permissions", which by default had "Read repository contents and packages permissions"

**Comment by onedr0p** [comment]
Interesting, I'll reopen the issue and hopefully someone can provide a better fix.

**Comment by onedr0p** [comment]
I just made [this change](https://github.com/onedr0p/flux-cluster-template/commit/929fdbd1b512ab41435cc9386af751179b8358fd) which is documented [here](https://github.com/actions/labeler#create-workflow)

**Comment by onedr0p** [comment]
That's unfortunate, I'm not sure how to solve this without clicking thru that config :/

**Comment by gavinmcfall** [comment]
If anyone else comes across this issue and is not actually sure how to fix it.

1. In Github, go into your Repository
2. Click "Settings" in the top menu
3. In the new left menu scroll down until you see "Actions" and expand that menu
4. Click "General"
5. Scroll down under these settings until you find: "Workflow permissions"
6. Set Permissions to "Read and Write Permissions" and click "Save".
7. In the top menu, Click "Actions"
8. In the left Menu click "Label Sync"
9. On the right side of the screen click the drop down "Run Workflow"
10. Click the blue button "Run Workflow"
11. After a few seconds you should see a new run of this action and it should pass
