### ISSUE TITLE
Clean deployment on Ubunu 22.04 fails with coredns pod crashloop backoff 

### ISSUE THREAD

**Issue by scuffe82** [onedr0p/flux-cluster-template#649]
I tried to setup a fresh 22.04 physical server today and i can't seem to get k3s to come up. The issue seems to be with coredns getting stuck in a crashloop backoff due to a dns loop error. I tried both fixing the /etc/resolv.conf file by pointing it to the real resolv.conf and also disabling systemd-resolvd and creating a new /etc/resolv.conf file. I rebooted and deleted the pod after both attempts. The configmap for coredns shows that it should be pointing to the resolv.conf file but nothing i do seem to make it not think its in a loop. This is a single host to start but will have additional nodes added once i get everything working on this one. 

This is the log output from the coredns pod

```
kubectl logs -n kube-system coredns-5c6b6c5476-749z9                                                    
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server .:53
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[INFO] plugin/reload: Running configuration SHA512 = b941b080e5322f6519009bb49349462c7ddb6317425b0f6a83e5451175b720703949e3f3b454a24e77f3ffe57fd5e9c6130e528a5a1dd00d9000e4afd6c1108d
CoreDNS-1.9.4
linux/amd64, go1.19.1, 1f0a41a
[FATAL] plugin/loop: Loop (127.0.0.1:60941 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 1167059398160673216.2231339636826385771."
```

Contents of /etc/resolv.conf on the physical host

```
cat /etc/resolv.conf
search mydomain.com
nameserver X.X.X.X
```

I tested the quickstart script from the k3s site and it did successfully come up in a base configuration. Any suggestions? Thanks!

**Comment by onedr0p** [comment]
Try updating your files, I just reverted this PR which might be related.

https://github.com/onedr0p/flux-cluster-template/pull/650

**Comment by LilDrunkenSmurf** [comment]
I had the same issue. The revert resolved it for me with an Ubuntu master node. Thanks!
