### ISSUE TITLE
task ansible:install fails on k3s hashsum check with Temporary failure in name resolution k3s checksum

### ISSUE THREAD

**Issue by corticalstack** [onedr0p/flux-cluster-template#670]
Running the following according to the step-by-step:

`task ansible:install`

- Which gives the error output pasted below. I have SSH'd onto the nodes (Proxmox VMs) and cannot resolve to gihub.com nor ping 8.8.8.8 (network is unreachable).
- I SSH into another fresh server built from same Ubuntu cloud init template and can resolve to GitHub, ping 8.8.8.8.

Sorry I don't know enough to consider if the playbook has broken/blocked the configured k3s nodes network connectivity.

```
TASK [xanmanning.k3s : Ensure the k3s hashsum is downloaded] ***********************************************************
fatal: [kube-worker1]: FAILED! => changed=false
  content: ''
  elapsed: 11
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>'
  redirected: false
  status: -1
  url: https://github.com/k3s-io/k3s/releases/download/v1.26.2+k3s1/sha256sum-amd64.txt
```

**Comment by onedr0p** [comment]
The template here doesn't modify any networking or DNS settings on the hosts that would cause you to lose connectivity.

**Comment by corticalstack** [comment]
Closed, re-provisioned VMs, passed that error, thanks
