### ISSUE TITLE
New cert-manager dashboard URL is wrong

### ISSUE THREAD

**Issue by Ramblurr** [onedr0p/flux-cluster-template#754]
https://github.com/onedr0p/flux-cluster-template/blob/2899466303fe48dfdeb6650be4b6ff81c7ee49d1/kubernetes/apps/cert-manager/cert-manager/app/kustomization.yaml#L11

That url goes to the HTML gitlab page.. it should be 

https://gitlab.com/uneeq-oss/cert-manager-mixin/-/raw/master/dashboards/cert-manager.json

**Comment by onedr0p** [comment]
Thanks, fixed https://github.com/onedr0p/flux-cluster-template/commit/5b9468dcd2ab7cf60877d7646d005a5ee895b9ac
