### ISSUE TITLE
IPv6 is disabled by default

### ISSUE THREAD

**Issue by samip5** [onedr0p/flux-cluster-template#851]
The cluster should have both enabled as that's stable in Kubernetes 1.23+.

There should at least be optional way to configure it in the template.

**Comment by onedr0p** [comment]
I'm open to contributions here!

**Comment by onedr0p** [comment]
Since there is already a discussion on this issue I'm going to close this issue. Looks to be like it can be revisited when Cilium supports ipv6.

https://github.com/onedr0p/flux-cluster-template/discussions/604

**Comment by samip5** [comment]
> Looks to be like it can be revisited when Cilium supports ipv6?

It does support it though?
