### ISSUE TITLE
Can't open url with bootstrap_k8s_gateway_addr

### ISSUE THREAD

**Issue by kchou94** [onedr0p/flux-cluster-template#925]
When i set bootstrap_k8s_gateway_addr on router, I can't open internel server
```sh
# /etc/dnsmasq.d/99-k8s-gateway-forward.conf
server=/${bootstrap_cloudflare_domain}/${bootstrap_k8s_gateway_addr}
```

But when i use `bootstrap_internal_ingress_addr`, it's works

**Comment by onedr0p** [comment]
Thanks for reporting but I think you should share your experience in https://github.com/onedr0p/flux-cluster-template/discussions/719

DNS is wildly different for everyone :/
