### ISSUE TITLE
Ability to bypass validation tasks if node IPv4 addresses are public

### ISSUE THREAD

**Issue by samip5** [onedr0p/flux-cluster-template#933]
The validation should take into account if a user specifies public addresses instead for nodes as they might be in a private LAN, but only accessible via public IP (or bastion host) for SSH

**Comment by onedr0p** [comment]
Not a bad idea, I guess you can bypass it if the IPs aren't RFC1918 and whatever the IPv6 equivalent is?

**Comment by samip5** [comment]
Hmm, I'm thinking if it should just be a new field under nodes? Like internal IP and external? Internal should always be specified but external not?
