### ISSUE TITLE
Task configure fails on Set reachable address

### ISSUE THREAD

**Issue by filipweilid** [onedr0p/flux-cluster-template#940]
The PR #938 isn't working, it seems like `loop` doesn't work with `set_fact` 

`TASK [Set reachable address] *************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined. 'item' is undefined\n\nThe error appears to be in '/Users/filipweilid/Projects/k3s-homelab/bootstrap/tasks/validation/net.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Set reachable address\n  ^ here\n"}`

**Comment by onedr0p** [comment]
@samip5 do you have time to take a look at this?

**Comment by samip5** [comment]
AAh, yeah. I have fix already. Forgot to submit it. :)
