### ISSUE TITLE
task ansible:install fails on Check if Coredns HelmChart exists

### ISSUE THREAD

**Issue by dalekurt** [onedr0p/flux-cluster-template#962]
My `task ansible:install` has failed on the master (control-plane) with the following message:

```sh
TASK [Coredns | Check if Coredns HelmChart exists] **********************************************************************
fatal: [control-plane]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (kubernetes) on control-plane's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

I've attempted to update the hosts.yaml to include the following `ansible_python_interpreter: /usr/bin/python3`. However the result was the same.

Any help on this would be appreciated

**Comment by onedr0p** [comment]
Did you try googling the error? My guess is that you don't have the right python libraries installed on the hosts which are part of the prepare step.

**Comment by dalekurt** [comment]
Started with Google first, but I was hesitant to make manual changes prior to reaching out first. I anticipated there being a task to settle any dependencies on the host coming from a vanilla state.

**Comment by onedr0p** [comment]
You didn't answer my question ... are you sure you ran the `ansible:prepare` task?

**Comment by dalekurt** [comment]
@onedr0p I don't know how I missed that. 🤦🏽‍♂️ That's what I get for juggling a baby and a keyboard. Thank you.

**Comment by onedr0p** [comment]
No worries I've been there 😄
