### ISSUE TITLE
`task ansible:prepare` fails if apparmor is not installed

### ISSUE THREAD

**Issue by b-** [onedr0p/flux-cluster-template#990]
I'm installing on a bare Debian image that I created using a preseed file, and it doesn't have the AppArmor service installed in the first place. As a result, the `ansible:prepare` task fails when it gets to that stage. 

```console
TASK [System Configuration | Disable apparmor] ***************************************************
fatal: [k3s-worker-02]: FAILED! => {"changed": false, "msg": "Could not find the requested service apparmor: host"}
fatal: [k3s-controller-01]: FAILED! => {"changed": false, "msg": "Could not find the requested service apparmor: host"}
```

I'm getting around this by commenting out the disable apparmor task in the ansible playbook, but I'm wondering if it would make sense to put a check for if the service exists.

**Comment by onedr0p** [comment]
Are you using stock debian 12 or some variation? Apparmor has been enabled by definitely since debian 10.

**Comment by b-** [comment]
> Are you using stock debian 12 or some variation? Apparmor has been enabled by default since debian 10.

Debian 12, but I installed using a preseed file (I updated [this repository](https://github.com/sdhibit/packer-proxmox-templates/blob/main/debian-12-amd64/templates/preseed.cfg.pkrtpl) for the Debian 12.2 release, which reminds me I should actually commit my changes and open a PR there...)

So I actually was starting with a stock Debian 12.2 ISO (specifically [this one](http://cdimage.debian.org/mirror/cdimage/release/12.2.0/amd64/iso-cd/debian-12.2.0-amd64-netinst.iso)), and calling it a "variation" would surely be a stretch. 

It's similar to what you'd get with debootstrap, but the preseed file drives the Debian Installer rather than directly driving dpkg...

**Comment by onedr0p** [comment]
No worries, the readme specifically states to use the full server DVD, not the net-install version. I have merged in your changes as it should help out people in the future that choose to use the net-install version. Hopefully there aren't any more gotchas for you with that 😄

**Comment by b-** [comment]
> No worries, the readme specifically states to use the full server DVD, not the net-install version. I have merged in your changes as it should help out people in the future that choose to use the net-install version. Hopefully there aren't any more gotchas for you with that 😄 . Thanks 👍🏼

Huh, I didn't realize _that_ was the reason I didn't end up with AppArmor! Thanks for letting me know too!

I'm still trying to wrap my head around it all well enough to really know if there are any issues or not, but so far so good!
